source "https://rubygems.org"

ruby "~> 3.4.0"

gem "csv"
gem "puma", "~> 7.0"
gem "rails", "~> 8.0"
gem "redis"
gem "sidekiq", "~> 8.0"
gem "speedshop-cloudwatch", path: ".."
gem "webmock"
gem "yabeda"
gem "yabeda-puma-plugin", require: false
gem "yabeda-rack-queue", require: false
gem "yabeda-sidekiq", require: false

group :development, :test do
  gem "debug"
end
